name: flutter_databinding
description: >
  Databinding for flutter.
version: 0.0.1
author: Arxing
homepage: https://github.com/Arxing/flutter-databinding

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
